// General MIDI 标准音色表：128 个旋律音色，按 16 个族分组，每组 8 个。
// 顺序严格遵循 GM 规范，program 号可直接用于 MIDI Program Change。
// 与手机端 FuMiVoice 的 GmInstruments 保持一致，供「轨道音色选择」使用。

export const GM_FAMILIES = [
  '钢琴', '色彩打击', '风琴', '吉他', '贝斯', '弦乐', '合奏', '铜管',
  '簧管', '吹管', '合成主音', '合成铺底', '合成效果', '民族乐器', '打击乐', '音效',
];

export const GM_INSTRUMENTS = [
  // 1-8 钢琴
  ['大钢琴', 'Acoustic Grand Piano'],
  ['明亮钢琴', 'Bright Acoustic Piano'],
  ['电钢琴', 'Electric Grand Piano'],
  ['酒吧钢琴', 'Honky-tonk Piano'],
  ['电钢琴 1', 'Electric Piano 1'],
  ['电钢琴 2', 'Electric Piano 2'],
  ['大键琴', 'Harpsichord'],
  ['击弦古钢琴', 'Clavinet'],
  // 9-16 色彩打击
  ['钢片琴', 'Celesta'],
  ['钟琴', 'Glockenspiel'],
  ['八音盒', 'Music Box'],
  ['颤音琴', 'Vibraphone'],
  ['马林巴', 'Marimba'],
  ['木琴', 'Xylophone'],
  ['管钟', 'Tubular Bells'],
  ['扬琴', 'Dulcimer'],
  // 17-24 风琴
  ['拉杆风琴', 'Drawbar Organ'],
  ['打击风琴', 'Percussive Organ'],
  ['摇滚风琴', 'Rock Organ'],
  ['教堂管风琴', 'Church Organ'],
  ['簧风琴', 'Reed Organ'],
  ['手风琴', 'Accordion'],
  ['口琴', 'Harmonica'],
  ['探戈手风琴', 'Tango Accordion'],
  // 25-32 吉他
  ['尼龙弦吉他', 'Acoustic Guitar (nylon)'],
  ['钢弦吉他', 'Acoustic Guitar (steel)'],
  ['爵士电吉他', 'Electric Guitar (jazz)'],
  ['清音电吉他', 'Electric Guitar (clean)'],
  ['闷音电吉他', 'Electric Guitar (muted)'],
  ['过载吉他', 'Overdriven Guitar'],
  ['失真吉他', 'Distortion Guitar'],
  ['吉他泛音', 'Guitar Harmonics'],
  // 33-40 贝斯
  ['原声贝斯', 'Acoustic Bass'],
  ['指弹电贝斯', 'Electric Bass (finger)'],
  ['拨片电贝斯', 'Electric Bass (pick)'],
  ['无品贝斯', 'Fretless Bass'],
  ['击弦贝斯 1', 'Slap Bass 1'],
  ['击弦贝斯 2', 'Slap Bass 2'],
  ['合成贝斯 1', 'Synth Bass 1'],
  ['合成贝斯 2', 'Synth Bass 2'],
  // 41-48 弦乐
  ['小提琴', 'Violin'],
  ['中提琴', 'Viola'],
  ['大提琴', 'Cello'],
  ['低音提琴', 'Contrabass'],
  ['颤弓弦乐', 'Tremolo Strings'],
  ['拨弦弦乐', 'Pizzicato Strings'],
  ['竖琴', 'Orchestral Harp'],
  ['定音鼓', 'Timpani'],
  // 49-56 合奏
  ['弦乐合奏 1', 'String Ensemble 1'],
  ['弦乐合奏 2', 'String Ensemble 2'],
  ['合成弦乐 1', 'Synth Strings 1'],
  ['合成弦乐 2', 'Synth Strings 2'],
  ['人声合唱', 'Choir Aahs'],
  ['人声呓语', 'Voice Oohs'],
  ['合成人声', 'Synth Voice'],
  ['管弦乐齐奏', 'Orchestra Hit'],
  // 57-64 铜管
  ['小号', 'Trumpet'],
  ['长号', 'Trombone'],
  ['大号', 'Tuba'],
  ['弱音小号', 'Muted Trumpet'],
  ['圆号', 'French Horn'],
  ['铜管合奏', 'Brass Section'],
  ['合成铜管 1', 'Synth Brass 1'],
  ['合成铜管 2', 'Synth Brass 2'],
  // 65-72 簧管
  ['高音萨克斯', 'Soprano Sax'],
  ['中音萨克斯', 'Alto Sax'],
  ['次中音萨克斯', 'Tenor Sax'],
  ['上低音萨克斯', 'Baritone Sax'],
  ['双簧管', 'Oboe'],
  ['英国管', 'English Horn'],
  ['巴松管', 'Bassoon'],
  ['单簧管', 'Clarinet'],
  // 73-80 吹管
  ['短笛', 'Piccolo'],
  ['长笛', 'Flute'],
  ['竖笛', 'Recorder'],
  ['排箫', 'Pan Flute'],
  ['瓶笛', 'Blown Bottle'],
  ['尺八', 'Shakuhachi'],
  ['口哨', 'Whistle'],
  ['陶笛', 'Ocarina'],
  // 81-88 合成主音
  ['方波主音', 'Lead 1 (square)'],
  ['锯齿主音', 'Lead 2 (sawtooth)'],
  ['汽笛风琴主音', 'Lead 3 (calliope)'],
  ['吹管主音', 'Lead 4 (chiff)'],
  ['人声主音', 'Lead 5 (charang)'],
  ['合唱主音', 'Lead 6 (voice)'],
  ['五度主音', 'Lead 7 (fifths)'],
  ['贝斯主音', 'Lead 8 (bass + lead)'],
  // 89-96 合成铺底
  ['新世纪铺底', 'Pad 1 (new age)'],
  ['温暖铺底', 'Pad 2 (warm)'],
  ['复音铺底', 'Pad 3 (polysynth)'],
  ['合唱铺底', 'Pad 4 (choir)'],
  ['弓弦铺底', 'Pad 5 (bowed)'],
  ['金属铺底', 'Pad 6 (metallic)'],
  ['光晕铺底', 'Pad 7 (halo)'],
  ['扫掠铺底', 'Pad 8 (sweep)'],
  // 97-104 合成效果
  ['雨声', 'FX 1 (rain)'],
  ['配乐', 'FX 2 (soundtrack)'],
  ['水晶', 'FX 3 (crystal)'],
  ['氛围', 'FX 4 (atmosphere)'],
  ['明亮', 'FX 5 (brightness)'],
  ['妖精', 'FX 6 (goblins)'],
  ['回声', 'FX 7 (echoes)'],
  ['科幻', 'FX 8 (sci-fi)'],
  // 105-112 民族乐器
  ['西塔琴', 'Sitar'],
  ['班卓琴', 'Banjo'],
  ['三味线', 'Shamisen'],
  ['古筝', 'Koto'],
  ['卡林巴', 'Kalimba'],
  ['风笛', 'Bagpipe'],
  ['乡村提琴', 'Fiddle'],
  ['唢呐', 'Shanai'],
  // 113-120 打击乐
  ['铃铛', 'Tinkle Bell'],
  ['阿哥哥铃', 'Agogo'],
  ['钢鼓', 'Steel Drums'],
  ['木鱼', 'Woodblock'],
  ['太鼓', 'Taiko Drum'],
  ['旋律鼓', 'Melodic Tom'],
  ['合成鼓', 'Synth Drum'],
  ['反镲', 'Reverse Cymbal'],
  // 121-128 音效
  ['吉他品丝噪音', 'Guitar Fret Noise'],
  ['呼吸声', 'Breath Noise'],
  ['海浪', 'Seashore'],
  ['鸟鸣', 'Bird Tweet'],
  ['电话铃', 'Telephone Ring'],
  ['直升机', 'Helicopter'],
  ['掌声', 'Applause'],
  ['枪声', 'Gunshot'],
].map(([name, englishName], index) => ({
  program: index,
  name,
  englishName,
  family: GM_FAMILIES[Math.floor(index / 8)],
}));

/** 按 program 号取音色；非法返回 null */
export function gmByProgram(program) {
  return GM_INSTRUMENTS[program] || null;
}